"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { EmptyState, PageHeader } from "@/components/exam-ui";
import type { ExamMockExam } from "@/lib/exam-os-types";

const labels = { accounting_score: "中级会计实务", finance_score: "财务管理", law_score: "经济法" } as const;
const colors = { accounting_score: "text-blue-600", finance_score: "text-orange-500", law_score: "text-emerald-600" } as const;

function average(item: ExamMockExam) { return Math.round(((item.accounting_score + item.finance_score + item.law_score) / 3) * 10) / 10; }
function weakest(item: ExamMockExam) { return (Object.keys(labels) as Array<keyof typeof labels>).sort((a, b) => item[a] - item[b])[0]; }

export function MockExamsManager({ initialExams }: { initialExams: ExamMockExam[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<ExamMockExam | null>(null); const [selectedId, setSelectedId] = useState(initialExams[0]?.id ?? ""); const [error, setError] = useState("");
  const selected = initialExams.find((item) => item.id === selectedId) ?? initialExams[0] ?? null;
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const input = { date: form.get("date"), accounting_score: Number(form.get("accounting_score")), finance_score: Number(form.get("finance_score")), law_score: Number(form.get("law_score")) }; const response = await fetch("/api/exam-os/mock-exams", { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(editing ? { id: editing.id, ...input } : input) }); if (!response.ok) { const data = await response.json(); setError(data.error ?? "保存失败"); return; } setOpen(false); setEditing(null); startTransition(() => router.refresh()); }
  async function remove(item: ExamMockExam) { if (!window.confirm("确认删除这次模考记录吗？")) return; await fetch(`/api/exam-os/mock-exams?id=${item.id}`, { method: "DELETE" }); setSelectedId(""); startTransition(() => router.refresh()); }
  const maxScore = Math.max(...initialExams.flatMap((item) => [item.accounting_score, item.finance_score, item.law_score]), 100);
  return <div className="min-h-screen"><PageHeader eyebrow="Mock Exam" title="模考记录" description="模考只负责验证结果：记录三科成绩、识别最弱科目，并观察成绩趋势。" action={<button onClick={() => { setEditing(null); setOpen(true); }} className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white">+ 添加模考</button>} />
    <div className="mx-auto max-w-7xl space-y-5 p-4 sm:p-8">{error ? <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div> : null}{initialExams.length === 0 ? <EmptyState title="还没有模考记录" description="完成一套试卷后，录入三科成绩开始观察趋势。" /> : <div className="grid gap-5 lg:grid-cols-[0.55fr_1.45fr]">
      <div className="space-y-3">{initialExams.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={`w-full rounded-2xl border p-4 text-left shadow-sm ${selected?.id === item.id ? "border-blue-300 bg-blue-50" : "border-slate-200 bg-white"}`}><p className="text-sm font-semibold text-slate-900">{item.date}</p><div className="mt-3 flex items-end justify-between"><div><strong className="text-3xl text-blue-600">{average(item)}</strong><span className="ml-1 text-xs text-slate-400">平均分</span></div><span className="text-xs text-slate-500">最弱：{labels[weakest(item)]}</span></div></button>)}</div>
      {selected ? <div className="space-y-5"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-600">{selected.date} 模考详情</p><h2 className="mt-2 text-2xl font-bold text-slate-950">平均 {average(selected)} 分</h2></div><div className="flex gap-3"><button onClick={() => { setEditing(selected); setOpen(true); }} className="text-sm font-semibold text-blue-600">编辑</button><button onClick={() => remove(selected)} className="text-sm text-red-500">删除</button></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{(Object.keys(labels) as Array<keyof typeof labels>).map((key) => <div key={key} className="rounded-xl bg-slate-50 p-4"><span className="text-xs text-slate-500">{labels[key]}</span><strong className={`mt-2 block text-3xl ${colors[key]}`}>{selected[key]}</strong></div>)}</div><div className="mt-5 rounded-xl bg-orange-50 p-4 text-sm text-orange-800">当前最弱科目：<strong>{labels[weakest(selected)]}</strong>，建议回到 Dashboard 查看该科目的危险章节。</div></article>
        <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-950">成绩趋势</h2><div className="mt-6 flex h-48 items-end gap-4 overflow-x-auto border-b border-slate-100 px-2">{[...initialExams].reverse().map((item) => <div key={item.id} className="flex min-w-20 flex-1 items-end justify-center gap-1"><div className="w-4 rounded-t bg-blue-500" style={{ height: `${(item.accounting_score / maxScore) * 150}px` }} /><div className="w-4 rounded-t bg-orange-400" style={{ height: `${(item.finance_score / maxScore) * 150}px` }} /><div className="w-4 rounded-t bg-emerald-500" style={{ height: `${(item.law_score / maxScore) * 150}px` }} /><span className="absolute mt-6 text-[10px] text-slate-400">{item.date.slice(5)}</span></div>)}</div></article>
      </div> : null}
    </div>}</div>
    {open ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4 backdrop-blur-sm"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold text-slate-950">{editing ? "编辑模考" : "添加模考"}</h2><label className="mt-5 block text-sm">日期<input name="date" type="date" required defaultValue={editing?.date ?? new Date().toISOString().slice(0, 10)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label><div className="mt-4 grid gap-4 sm:grid-cols-3">{(Object.keys(labels) as Array<keyof typeof labels>).map((key) => <label key={key} className="text-sm">{labels[key]}<input name={key} type="number" min="0" max="100" step="0.5" required defaultValue={editing?.[key] ?? 60} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3" /></label>)}</div><div className="mt-6 flex gap-3"><button disabled={pending} className="flex-1 rounded-xl bg-blue-600 py-3 text-sm font-semibold text-white">保存</button><button type="button" onClick={() => setOpen(false)} className="rounded-xl border border-slate-200 px-5 text-sm">取消</button></div></form></div> : null}
  </div>;
}
